// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: carriers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCarrier = `-- name: CreateCarrier :one
INSERT INTO carriers (country_id, name, prefixes)
VALUES ($1, $2, $3::jsonb)
RETURNING id, country_id, name, prefixes, created_at
`

type CreateCarrierParams struct {
	CountryID uuid.UUID `json:"country_id"`
	Name      string    `json:"name"`
	Prefixes  []byte    `json:"prefixes"`
}

func (q *Queries) CreateCarrier(ctx context.Context, arg CreateCarrierParams) (Carrier, error) {
	row := q.db.QueryRow(ctx, createCarrier, arg.CountryID, arg.Name, arg.Prefixes)
	var i Carrier
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.Name,
		&i.Prefixes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCarrier = `-- name: DeleteCarrier :execrows
DELETE FROM carriers WHERE id = $1
`

func (q *Queries) DeleteCarrier(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCarrier, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCarrier = `-- name: GetCarrier :one
SELECT c.id, c.country_id, c.name, c.prefixes, c.created_at, co.code AS country_code
FROM carriers c
JOIN countries co ON co.id = c.country_id
WHERE c.id = $1
`

type GetCarrierRow struct {
	ID          uuid.UUID          `json:"id"`
	CountryID   uuid.UUID          `json:"country_id"`
	Name        string             `json:"name"`
	Prefixes    []byte             `json:"prefixes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CountryCode string             `json:"country_code"`
}

func (q *Queries) GetCarrier(ctx context.Context, id uuid.UUID) (GetCarrierRow, error) {
	row := q.db.QueryRow(ctx, getCarrier, id)
	var i GetCarrierRow
	err := row.Scan(
		&i.ID,
		&i.CountryID,
		&i.Name,
		&i.Prefixes,
		&i.CreatedAt,
		&i.CountryCode,
	)
	return i, err
}

const listCarriersByCountry = `-- name: ListCarriersByCountry :many
SELECT c.id, c.country_id, c.name, c.prefixes, c.created_at, co.code AS country_code
FROM carriers c
JOIN countries co ON co.id = c.country_id
WHERE c.country_id = $1
ORDER BY c.name
`

type ListCarriersByCountryRow struct {
	ID          uuid.UUID          `json:"id"`
	CountryID   uuid.UUID          `json:"country_id"`
	Name        string             `json:"name"`
	Prefixes    []byte             `json:"prefixes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CountryCode string             `json:"country_code"`
}

func (q *Queries) ListCarriersByCountry(ctx context.Context, countryID uuid.UUID) ([]ListCarriersByCountryRow, error) {
	rows, err := q.db.Query(ctx, listCarriersByCountry, countryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCarriersByCountryRow
	for rows.Next() {
		var i ListCarriersByCountryRow
		if err := rows.Scan(
			&i.ID,
			&i.CountryID,
			&i.Name,
			&i.Prefixes,
			&i.CreatedAt,
			&i.CountryCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
