// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: countries.sql

package db

import (
	"context"
)

const createCountry = `-- name: CreateCountry :one
INSERT INTO countries (code, phone_code, total_digits)
VALUES ($1, $2, $3)
RETURNING id, code, phone_code, total_digits, created_at
`

type CreateCountryParams struct {
	Code        string `json:"code"`
	PhoneCode   string `json:"phone_code"`
	TotalDigits int32  `json:"total_digits"`
}

func (q *Queries) CreateCountry(ctx context.Context, arg CreateCountryParams) (Country, error) {
	row := q.db.QueryRow(ctx, createCountry, arg.Code, arg.PhoneCode, arg.TotalDigits)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PhoneCode,
		&i.TotalDigits,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCountry = `-- name: DeleteCountry :execrows
DELETE FROM countries WHERE code = $1
`

func (q *Queries) DeleteCountry(ctx context.Context, code string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCountry, code)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCountryByCode = `-- name: GetCountryByCode :one
SELECT id, code, phone_code, total_digits, created_at FROM countries WHERE code = $1
`

func (q *Queries) GetCountryByCode(ctx context.Context, code string) (Country, error) {
	row := q.db.QueryRow(ctx, getCountryByCode, code)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PhoneCode,
		&i.TotalDigits,
		&i.CreatedAt,
	)
	return i, err
}

const listCountries = `-- name: ListCountries :many
SELECT id, code, phone_code, total_digits, created_at FROM countries ORDER BY code
`

func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.PhoneCode,
			&i.TotalDigits,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
