// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flows.sql

package db

import (
	"context"
)

const createFlow = `-- name: CreateFlow :one
INSERT INTO flows (id, name, active, input_contract)
VALUES ($1, $2, $3, $4::jsonb)
RETURNING id, name, active, input_contract, created_at, updated_at
`

type CreateFlowParams struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Active        bool   `json:"active"`
	InputContract []byte `json:"input_contract"`
}

func (q *Queries) CreateFlow(ctx context.Context, arg CreateFlowParams) (Flow, error) {
	row := q.db.QueryRow(ctx, createFlow,
		arg.ID,
		arg.Name,
		arg.Active,
		arg.InputContract,
	)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.InputContract,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFlow = `-- name: DeleteFlow :execrows
DELETE FROM flows WHERE id = $1
`

func (q *Queries) DeleteFlow(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFlow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFlow = `-- name: GetFlow :one
SELECT id, name, active, input_contract, created_at, updated_at
FROM flows WHERE id = $1
`

func (q *Queries) GetFlow(ctx context.Context, id string) (Flow, error) {
	row := q.db.QueryRow(ctx, getFlow, id)
	var i Flow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.InputContract,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFlows = `-- name: ListFlows :many
SELECT id, name, active, input_contract, created_at, updated_at
FROM flows ORDER BY created_at DESC
`

func (q *Queries) ListFlows(ctx context.Context) ([]Flow, error) {
	rows, err := q.db.Query(ctx, listFlows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Flow
	for rows.Next() {
		var i Flow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.InputContract,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlow = `-- name: UpdateFlow :exec
UPDATE flows
SET name = $2, active = $3, input_contract = $4::jsonb, updated_at = now()
WHERE id = $1
`

type UpdateFlowParams struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Active        bool   `json:"active"`
	InputContract []byte `json:"input_contract"`
}

func (q *Queries) UpdateFlow(ctx context.Context, arg UpdateFlowParams) error {
	_, err := q.db.Exec(ctx, updateFlow,
		arg.ID,
		arg.Name,
		arg.Active,
		arg.InputContract,
	)
	return err
}
