// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flow_channels.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFlowChannel = `-- name: CreateFlowChannel :one
INSERT INTO flow_channels (flow_id, channel, enabled, uses_template, template_name, template_param_order, default_content, required_variables, channel_config)
VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::jsonb, $8::jsonb, $9::jsonb)
RETURNING id, flow_id, channel, enabled, uses_template, template_name, template_param_order, default_content, required_variables, channel_config, created_at
`

type CreateFlowChannelParams struct {
	FlowID             string      `json:"flow_id"`
	Channel            string      `json:"channel"`
	Enabled            bool        `json:"enabled"`
	UsesTemplate       bool        `json:"uses_template"`
	TemplateName       pgtype.Text `json:"template_name"`
	TemplateParamOrder []byte      `json:"template_param_order"`
	DefaultContent     []byte      `json:"default_content"`
	RequiredVariables  []byte      `json:"required_variables"`
	ChannelConfig      []byte      `json:"channel_config"`
}

func (q *Queries) CreateFlowChannel(ctx context.Context, arg CreateFlowChannelParams) (FlowChannel, error) {
	row := q.db.QueryRow(ctx, createFlowChannel,
		arg.FlowID,
		arg.Channel,
		arg.Enabled,
		arg.UsesTemplate,
		arg.TemplateName,
		arg.TemplateParamOrder,
		arg.DefaultContent,
		arg.RequiredVariables,
		arg.ChannelConfig,
	)
	var i FlowChannel
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Channel,
		&i.Enabled,
		&i.UsesTemplate,
		&i.TemplateName,
		&i.TemplateParamOrder,
		&i.DefaultContent,
		&i.RequiredVariables,
		&i.ChannelConfig,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFlowChannel = `-- name: DeleteFlowChannel :execrows
DELETE FROM flow_channels WHERE id = $1
`

func (q *Queries) DeleteFlowChannel(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFlowChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFlowChannel = `-- name: GetFlowChannel :one
SELECT id, flow_id, channel, enabled, uses_template, template_name, template_param_order, default_content, required_variables, channel_config, created_at
FROM flow_channels WHERE id = $1
`

func (q *Queries) GetFlowChannel(ctx context.Context, id uuid.UUID) (FlowChannel, error) {
	row := q.db.QueryRow(ctx, getFlowChannel, id)
	var i FlowChannel
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Channel,
		&i.Enabled,
		&i.UsesTemplate,
		&i.TemplateName,
		&i.TemplateParamOrder,
		&i.DefaultContent,
		&i.RequiredVariables,
		&i.ChannelConfig,
		&i.CreatedAt,
	)
	return i, err
}

const listFlowChannels = `-- name: ListFlowChannels :many
SELECT id, flow_id, channel, enabled, uses_template, template_name, template_param_order, default_content, required_variables, channel_config, created_at
FROM flow_channels WHERE flow_id = $1 ORDER BY channel
`

func (q *Queries) ListFlowChannels(ctx context.Context, flowID string) ([]FlowChannel, error) {
	rows, err := q.db.Query(ctx, listFlowChannels, flowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FlowChannel
	for rows.Next() {
		var i FlowChannel
		if err := rows.Scan(
			&i.ID,
			&i.FlowID,
			&i.Channel,
			&i.Enabled,
			&i.UsesTemplate,
			&i.TemplateName,
			&i.TemplateParamOrder,
			&i.DefaultContent,
			&i.RequiredVariables,
			&i.ChannelConfig,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFlowChannel = `-- name: UpdateFlowChannel :exec
UPDATE flow_channels
SET enabled = $2, uses_template = $3, template_name = $4, template_param_order = $5::jsonb,
    default_content = $6::jsonb, required_variables = $7::jsonb,
    channel_config = $8::jsonb
WHERE id = $1
`

type UpdateFlowChannelParams struct {
	ID                 uuid.UUID   `json:"id"`
	Enabled            bool        `json:"enabled"`
	UsesTemplate       bool        `json:"uses_template"`
	TemplateName       pgtype.Text `json:"template_name"`
	TemplateParamOrder []byte      `json:"template_param_order"`
	DefaultContent     []byte      `json:"default_content"`
	RequiredVariables  []byte      `json:"required_variables"`
	ChannelConfig      []byte      `json:"channel_config"`
}

func (q *Queries) UpdateFlowChannel(ctx context.Context, arg UpdateFlowChannelParams) error {
	_, err := q.db.Exec(ctx, updateFlowChannel,
		arg.ID,
		arg.Enabled,
		arg.UsesTemplate,
		arg.TemplateName,
		arg.TemplateParamOrder,
		arg.DefaultContent,
		arg.RequiredVariables,
		arg.ChannelConfig,
	)
	return err
}

const upsertFlowChannel = `-- name: UpsertFlowChannel :one
INSERT INTO flow_channels (flow_id, channel, enabled, uses_template, template_name, template_param_order, default_content, required_variables, channel_config)
VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7::jsonb, $8::jsonb, $9::jsonb)
ON CONFLICT (flow_id, channel) DO UPDATE SET
    enabled = EXCLUDED.enabled,
    uses_template = EXCLUDED.uses_template,
    template_name = EXCLUDED.template_name,
    template_param_order = EXCLUDED.template_param_order,
    default_content = EXCLUDED.default_content,
    required_variables = EXCLUDED.required_variables,
    channel_config = EXCLUDED.channel_config
RETURNING id, flow_id, channel, enabled, uses_template, template_name, template_param_order, default_content, required_variables, channel_config, created_at
`

type UpsertFlowChannelParams struct {
	FlowID             string      `json:"flow_id"`
	Channel            string      `json:"channel"`
	Enabled            bool        `json:"enabled"`
	UsesTemplate       bool        `json:"uses_template"`
	TemplateName       pgtype.Text `json:"template_name"`
	TemplateParamOrder []byte      `json:"template_param_order"`
	DefaultContent     []byte      `json:"default_content"`
	RequiredVariables  []byte      `json:"required_variables"`
	ChannelConfig      []byte      `json:"channel_config"`
}

func (q *Queries) UpsertFlowChannel(ctx context.Context, arg UpsertFlowChannelParams) (FlowChannel, error) {
	row := q.db.QueryRow(ctx, upsertFlowChannel,
		arg.FlowID,
		arg.Channel,
		arg.Enabled,
		arg.UsesTemplate,
		arg.TemplateName,
		arg.TemplateParamOrder,
		arg.DefaultContent,
		arg.RequiredVariables,
		arg.ChannelConfig,
	)
	var i FlowChannel
	err := row.Scan(
		&i.ID,
		&i.FlowID,
		&i.Channel,
		&i.Enabled,
		&i.UsesTemplate,
		&i.TemplateName,
		&i.TemplateParamOrder,
		&i.DefaultContent,
		&i.RequiredVariables,
		&i.ChannelConfig,
		&i.CreatedAt,
	)
	return i, err
}
