// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Carrier struct {
	ID        uuid.UUID          `json:"id"`
	CountryID uuid.UUID          `json:"country_id"`
	Name      string             `json:"name"`
	Prefixes  []byte             `json:"prefixes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Country struct {
	ID          uuid.UUID          `json:"id"`
	Code        string             `json:"code"`
	PhoneCode   string             `json:"phone_code"`
	TotalDigits int32              `json:"total_digits"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Flow struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Active        bool               `json:"active"`
	InputContract []byte             `json:"input_contract"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type FlowChannel struct {
	ID                 uuid.UUID          `json:"id"`
	FlowID             string             `json:"flow_id"`
	Channel            string             `json:"channel"`
	Enabled            bool               `json:"enabled"`
	UsesTemplate       bool               `json:"uses_template"`
	TemplateName       pgtype.Text        `json:"template_name"`
	TemplateParamOrder []byte             `json:"template_param_order"`
	DefaultContent     []byte             `json:"default_content"`
	RequiredVariables  []byte             `json:"required_variables"`
	ChannelConfig      []byte             `json:"channel_config"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Provider struct {
	ID          string             `json:"id"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ProviderCountryPricing struct {
	ID                uuid.UUID          `json:"id"`
	ProviderID        string             `json:"provider_id"`
	Channel           string             `json:"channel"`
	CountryID         *uuid.UUID         `json:"country_id"`
	CarrierID         *uuid.UUID         `json:"carrier_id"`
	VolumeResetPeriod string             `json:"volume_reset_period"`
	VolumeResetDays   pgtype.Int4        `json:"volume_reset_days"`
	VolumeResetAnchor pgtype.Date        `json:"volume_reset_anchor"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ProviderCountryPricingTier struct {
	ID        uuid.UUID          `json:"id"`
	PricingID uuid.UUID          `json:"pricing_id"`
	MinVolume int64              `json:"min_volume"`
	MaxVolume int64              `json:"max_volume"`
	TierPrice string             `json:"tier_price"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
