// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pricing.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPricing = `-- name: CreatePricing :one
INSERT INTO provider_country_pricing
    (provider_id, channel, country_id, carrier_id, volume_reset_period, volume_reset_days, volume_reset_anchor)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, provider_id, channel, country_id, carrier_id, volume_reset_period, volume_reset_days, volume_reset_anchor, created_at
`

type CreatePricingParams struct {
	ProviderID        string      `json:"provider_id"`
	Channel           string      `json:"channel"`
	CountryID         *uuid.UUID  `json:"country_id"`
	CarrierID         *uuid.UUID  `json:"carrier_id"`
	VolumeResetPeriod string      `json:"volume_reset_period"`
	VolumeResetDays   pgtype.Int4 `json:"volume_reset_days"`
	VolumeResetAnchor pgtype.Date `json:"volume_reset_anchor"`
}

func (q *Queries) CreatePricing(ctx context.Context, arg CreatePricingParams) (ProviderCountryPricing, error) {
	row := q.db.QueryRow(ctx, createPricing,
		arg.ProviderID,
		arg.Channel,
		arg.CountryID,
		arg.CarrierID,
		arg.VolumeResetPeriod,
		arg.VolumeResetDays,
		arg.VolumeResetAnchor,
	)
	var i ProviderCountryPricing
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Channel,
		&i.CountryID,
		&i.CarrierID,
		&i.VolumeResetPeriod,
		&i.VolumeResetDays,
		&i.VolumeResetAnchor,
		&i.CreatedAt,
	)
	return i, err
}

const createTier = `-- name: CreateTier :one
INSERT INTO provider_country_pricing_tiers (pricing_id, min_volume, max_volume, tier_price)
VALUES ($1, $2, $3, $4)
RETURNING id, pricing_id, min_volume, max_volume, tier_price, created_at
`

type CreateTierParams struct {
	PricingID uuid.UUID `json:"pricing_id"`
	MinVolume int64     `json:"min_volume"`
	MaxVolume int64     `json:"max_volume"`
	TierPrice string    `json:"tier_price"`
}

func (q *Queries) CreateTier(ctx context.Context, arg CreateTierParams) (ProviderCountryPricingTier, error) {
	row := q.db.QueryRow(ctx, createTier,
		arg.PricingID,
		arg.MinVolume,
		arg.MaxVolume,
		arg.TierPrice,
	)
	var i ProviderCountryPricingTier
	err := row.Scan(
		&i.ID,
		&i.PricingID,
		&i.MinVolume,
		&i.MaxVolume,
		&i.TierPrice,
		&i.CreatedAt,
	)
	return i, err
}

const deletePricing = `-- name: DeletePricing :execrows
DELETE FROM provider_country_pricing WHERE id = $1
`

func (q *Queries) DeletePricing(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePricing, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTier = `-- name: DeleteTier :execrows
DELETE FROM provider_country_pricing_tiers WHERE id = $1 AND pricing_id = $2
`

type DeleteTierParams struct {
	ID        uuid.UUID `json:"id"`
	PricingID uuid.UUID `json:"pricing_id"`
}

func (q *Queries) DeleteTier(ctx context.Context, arg DeleteTierParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTier, arg.ID, arg.PricingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPricing = `-- name: GetPricing :one
SELECT p.id, p.provider_id, p.channel, p.country_id, p.carrier_id, p.volume_reset_period, p.volume_reset_days, p.volume_reset_anchor, p.created_at,
       c.code  AS country_code,
       cr.name AS carrier_name
FROM provider_country_pricing p
LEFT JOIN countries c ON c.id = p.country_id
LEFT JOIN carriers cr ON cr.id = p.carrier_id
WHERE p.id = $1
`

type GetPricingRow struct {
	ID                uuid.UUID          `json:"id"`
	ProviderID        string             `json:"provider_id"`
	Channel           string             `json:"channel"`
	CountryID         *uuid.UUID         `json:"country_id"`
	CarrierID         *uuid.UUID         `json:"carrier_id"`
	VolumeResetPeriod string             `json:"volume_reset_period"`
	VolumeResetDays   pgtype.Int4        `json:"volume_reset_days"`
	VolumeResetAnchor pgtype.Date        `json:"volume_reset_anchor"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CountryCode       pgtype.Text        `json:"country_code"`
	CarrierName       pgtype.Text        `json:"carrier_name"`
}

func (q *Queries) GetPricing(ctx context.Context, id uuid.UUID) (GetPricingRow, error) {
	row := q.db.QueryRow(ctx, getPricing, id)
	var i GetPricingRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Channel,
		&i.CountryID,
		&i.CarrierID,
		&i.VolumeResetPeriod,
		&i.VolumeResetDays,
		&i.VolumeResetAnchor,
		&i.CreatedAt,
		&i.CountryCode,
		&i.CarrierName,
	)
	return i, err
}

const listPricing = `-- name: ListPricing :many
SELECT p.id, p.provider_id, p.channel, p.country_id, p.carrier_id, p.volume_reset_period, p.volume_reset_days, p.volume_reset_anchor, p.created_at,
       c.code  AS country_code,
       cr.name AS carrier_name
FROM provider_country_pricing p
LEFT JOIN countries c ON c.id = p.country_id
LEFT JOIN carriers cr ON cr.id = p.carrier_id
WHERE ($1::text IS NULL OR p.provider_id = $1)
  AND ($2::text IS NULL OR p.channel = $2)
  AND ($3::char(2) IS NULL OR c.code = $3)
ORDER BY p.provider_id, p.channel, c.code NULLS FIRST
`

type ListPricingParams struct {
	ProviderID  pgtype.Text `json:"provider_id"`
	Channel     pgtype.Text `json:"channel"`
	CountryCode pgtype.Text `json:"country_code"`
}

type ListPricingRow struct {
	ID                uuid.UUID          `json:"id"`
	ProviderID        string             `json:"provider_id"`
	Channel           string             `json:"channel"`
	CountryID         *uuid.UUID         `json:"country_id"`
	CarrierID         *uuid.UUID         `json:"carrier_id"`
	VolumeResetPeriod string             `json:"volume_reset_period"`
	VolumeResetDays   pgtype.Int4        `json:"volume_reset_days"`
	VolumeResetAnchor pgtype.Date        `json:"volume_reset_anchor"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CountryCode       pgtype.Text        `json:"country_code"`
	CarrierName       pgtype.Text        `json:"carrier_name"`
}

func (q *Queries) ListPricing(ctx context.Context, arg ListPricingParams) ([]ListPricingRow, error) {
	rows, err := q.db.Query(ctx, listPricing, arg.ProviderID, arg.Channel, arg.CountryCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPricingRow
	for rows.Next() {
		var i ListPricingRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Channel,
			&i.CountryID,
			&i.CarrierID,
			&i.VolumeResetPeriod,
			&i.VolumeResetDays,
			&i.VolumeResetAnchor,
			&i.CreatedAt,
			&i.CountryCode,
			&i.CarrierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTiersByPricing = `-- name: ListTiersByPricing :many
SELECT id, pricing_id, min_volume, max_volume, tier_price, created_at
FROM provider_country_pricing_tiers
WHERE pricing_id = $1
ORDER BY min_volume
`

func (q *Queries) ListTiersByPricing(ctx context.Context, pricingID uuid.UUID) ([]ProviderCountryPricingTier, error) {
	rows, err := q.db.Query(ctx, listTiersByPricing, pricingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderCountryPricingTier
	for rows.Next() {
		var i ProviderCountryPricingTier
		if err := rows.Scan(
			&i.ID,
			&i.PricingID,
			&i.MinVolume,
			&i.MaxVolume,
			&i.TierPrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
