// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package db

import (
	"context"
)

const getProvider = `-- name: GetProvider :one
SELECT id, display_name, created_at FROM providers WHERE id = $1
`

func (q *Queries) GetProvider(ctx context.Context, id string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i Provider
	err := row.Scan(&i.ID, &i.DisplayName, &i.CreatedAt)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, display_name, created_at FROM providers ORDER BY id
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedProvider = `-- name: SeedProvider :one
INSERT INTO providers (id, display_name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET display_name = EXCLUDED.display_name
RETURNING id
`

type SeedProviderParams struct {
	ID          string `json:"id"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) SeedProvider(ctx context.Context, arg SeedProviderParams) (string, error) {
	row := q.db.QueryRow(ctx, seedProvider, arg.ID, arg.DisplayName)
	var id string
	err := row.Scan(&id)
	return id, err
}
